name : image-viewer-dev

channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r


dependencies:
  - python=3.11
  - pip
  - pyside6
  - pyqtgraph
  - pytorch
  - transformers
  - pyyaml
  - pillow
  - umap-learn
  - hdbscan
  - opencv
  - pip:
    - pyqtdarktheme
